"""add_admin_and_activity_flags_and_order_pickup_fields

Revision ID: 194085fbd5c4
Revises: 90275cf6dcbf
Create Date: 2025-05-23 05:35:38.459419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194085fbd5c4'
down_revision = '90275cf6dcbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picked_up_by_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('picked_up_by_id_no', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('picked_up_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('picked_up_at')
        batch_op.drop_column('picked_up_by_id_no')
        batch_op.drop_column('picked_up_by_name')

    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
