"""Ensure payment_transaction_id_in_orders

Revision ID: 90275cf6dcbf
Revises: fc9079f1c17f
Create Date: 2025-05-23 04:59:38.814120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90275cf6dcbf'
down_revision = 'fc9079f1c17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_pickup', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_option_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('delivery_fee', mysql.DECIMAL(precision=10, scale=2), nullable=False))
        batch_op.create_foreign_key(None, 'delivery_options', ['delivery_option_id'], ['id'])

    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_delivery_option_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('applied_delivery_fee', mysql.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.create_foreign_key(None, 'delivery_options', ['selected_delivery_option_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('applied_delivery_fee')
        batch_op.drop_column('selected_delivery_option_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('delivery_fee')
        batch_op.drop_column('delivery_option_id')

    op.drop_table('delivery_options')
    # ### end Alembic commands ###
