import type { Metadata } from "next";
import "./globals.css";
import { Playfair_Display, Montserrat, Lato } from 'next/font/google';

const playfair = Playfair_Display({ subsets: ['latin'], weight: '400' });
const montserrat = Montserrat({ subsets: ['latin'], weight: '400' });
const lato = Lato({ subsets: ['latin'], weight: '400' });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playfair.className} ${montserrat.className} ${lato.className}`}>
                {children}
            </body>
    </html>
  );
}
